/**
 * shrd - Output Formatter
 * Formats generated blog content into various output formats
 */

import type { 
  GeneratedBlog, 
  NormalizedContent, 
  ShrdOutput, 
  OutputFormat 
} from './types.js';
import { getPlatformName } from './router.js';

/**
 * Format the complete shrd output
 */
export function format(
  blog: GeneratedBlog,
  content: NormalizedContent,
  outputFormat: OutputFormat = 'markdown'
): ShrdOutput {
  const markdown = formatMarkdown(blog, content);
  
  return {
    blog,
    source: content.source,
    embed: content.media.embedCode,
    markdown,
  };
}

/**
 * Format as Markdown (primary output)
 */
export function formatMarkdown(blog: GeneratedBlog, content: NormalizedContent): string {
  const lines: string[] = [];
  
  // Title
  lines.push(`# ${blog.title}`);
  lines.push('');
  
  // Description
  lines.push(blog.description);
  lines.push('');
  
  // Key Insights
  if (blog.insights.length > 0) {
    lines.push('## Key Insights');
    lines.push('');
    for (const insight of blog.insights) {
      lines.push(`- 🎯 ${insight}`);
    }
    lines.push('');
  }
  
  // Notable Quotes
  if (blog.quotes.length > 0) {
    lines.push('## Notable Quotes');
    lines.push('');
    for (const quote of blog.quotes) {
      lines.push(`> "${quote}"`);
      lines.push('');
    }
  }
  
  // Mentions (if any)
  if (blog.mentions && blog.mentions.length > 0) {
    lines.push('## Mentioned');
    lines.push('');
    lines.push(blog.mentions.map(m => `\`${m}\``).join(' • '));
    lines.push('');
  }
  
  // Embed section
  lines.push(`## ${getWatchReadListenLabel(content.source.platform)}`);
  lines.push('');
  lines.push(content.media.embedCode);
  lines.push('');
  
  // Source attribution
  lines.push('---');
  lines.push(`*Source: ${getPlatformName(content.source.platform)} | ${content.source.title} | ${content.source.author}*`);
  if (content.source.date) {
    lines.push(`*Published: ${content.source.date}*`);
  }
  lines.push('*Generated by [shrd](https://shrd.co)*');
  
  return lines.join('\n');
}

/**
 * Format as HTML
 */
export function formatHtml(blog: GeneratedBlog, content: NormalizedContent): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(blog.title)}</title>
  <style>
    body {
      font-family: system-ui, -apple-system, sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
      line-height: 1.6;
      color: #333;
    }
    h1 { font-size: 2rem; margin-bottom: 0.5rem; }
    .description { font-size: 1.1rem; color: #555; margin-bottom: 2rem; }
    h2 { font-size: 1.5rem; margin-top: 2rem; border-bottom: 1px solid #eee; padding-bottom: 0.5rem; }
    ul { padding-left: 1.5rem; }
    li { margin-bottom: 0.5rem; }
    blockquote { 
      border-left: 3px solid #007acc; 
      padding-left: 1rem; 
      margin-left: 0;
      font-style: italic;
      color: #555;
    }
    .mentions { display: flex; gap: 0.5rem; flex-wrap: wrap; }
    .mention { 
      background: #f0f0f0; 
      padding: 0.25rem 0.5rem; 
      border-radius: 4px;
      font-size: 0.9rem;
    }
    .embed { margin: 2rem 0; }
    .source { 
      margin-top: 2rem; 
      padding-top: 1rem; 
      border-top: 1px solid #eee;
      font-size: 0.9rem;
      color: #666;
    }
  </style>
</head>
<body>
  <article>
    <h1>${escapeHtml(blog.title)}</h1>
    <p class="description">${escapeHtml(blog.description)}</p>
    
    ${blog.insights.length > 0 ? `
    <h2>Key Insights</h2>
    <ul>
      ${blog.insights.map(i => `<li>🎯 ${escapeHtml(i)}</li>`).join('\n      ')}
    </ul>
    ` : ''}
    
    ${blog.quotes.length > 0 ? `
    <h2>Notable Quotes</h2>
    ${blog.quotes.map(q => `<blockquote>"${escapeHtml(q)}"</blockquote>`).join('\n    ')}
    ` : ''}
    
    ${blog.mentions && blog.mentions.length > 0 ? `
    <h2>Mentioned</h2>
    <div class="mentions">
      ${blog.mentions.map(m => `<span class="mention">${escapeHtml(m)}</span>`).join('\n      ')}
    </div>
    ` : ''}
    
    <h2>${getWatchReadListenLabel(content.source.platform)}</h2>
    <div class="embed">
      ${content.media.embedCode}
    </div>
    
    <div class="source">
      <p>Source: ${getPlatformName(content.source.platform)} | ${escapeHtml(content.source.title)} | ${escapeHtml(content.source.author)}</p>
      ${content.source.date ? `<p>Published: ${content.source.date}</p>` : ''}
      <p>Generated by <a href="https://shrd.co">shrd</a></p>
    </div>
  </article>
</body>
</html>`;
}

/**
 * Format as JSON
 */
export function formatJson(blog: GeneratedBlog, content: NormalizedContent): string {
  return JSON.stringify({
    blog,
    source: content.source,
    embed: content.media.embedCode,
  }, null, 2);
}

/**
 * Get appropriate "Watch/Read/Listen" label based on platform
 */
function getWatchReadListenLabel(platform: string): string {
  switch (platform) {
    case 'youtube':
    case 'tiktok':
    case 'instagram':
      return 'Watch';
    case 'podcast':
      return 'Listen';
    case 'twitter':
      return 'View Thread';
    default:
      return 'Read';
  }
}

/**
 * Escape HTML entities
 */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/**
 * Generate filename from blog title
 */
export function generateFilename(title: string, format: OutputFormat = 'markdown'): string {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 50);
  
  const ext = format === 'markdown' ? 'md' : format === 'html' ? 'html' : 'json';
  const date = new Date().toISOString().split('T')[0];
  
  return `${date}-${slug}.${ext}`;
}
